Automatically install yq; better error handling

diff --git a/borgsetup b/borgsetup
--- a/borgsetup
+++ b/borgsetup
@@ -29,6 +29,11 @@ REMOTE_DIRECTORY=borg
 
 SCRIPT_DIR=$(dirname $(readlink -f $0))
 
+die() {
+    echo $2
+    exit $1
+}
+
 if [[ -d /etc/apt ]]; then
 	APT=true
 	SUDO=sudo
@@ -38,14 +43,9 @@ elif [[ -d /etc/yum ]]; then
 	SUDO=wheel
 	BORGMATIC=/usr/bin/borgmatic
 else
-	echo "Distribution not supported!"
-	exit -1
+	die -1 "Distribution not supported!"
 fi
 
-if ! yq . </dev/null 2>/dev/null; then
-    echo "yq not installed, aborting"
-    exit -1
-fi
 
 # Override defaults by sourcing config files. These are cumulative!
 if [[ -f /etc/borgsetup ]]; then
@@ -69,8 +69,7 @@ fi
 HOSTNAME=$(hostname)
 case "$HOSTNAME" in
 *localhost*|*localdomain*|*dedibox* )
-	echo "Your hostname $HOSTNAME is not configured properly, aborting"
-	exit 10
+	die 10 "Your hostname $HOSTNAME is not configured properly, aborting"
 	;;
 esac
 
@@ -78,13 +77,11 @@ if [[ "$REMOTE_HOST" ]]; then
 	REPO_LOCATION="${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_DIRECTORY}"
 elif [[ "$LOCAL_DIRECTORY" ]]; then
 	if [[ "$LOCAL_DIRECTORY" = "/" ]]; then
-		echo "Don't use / as your backup location! Aborting."
-		exit 1
+		die 1 "Don't use / as your backup location! Aborting."
 	fi
 	REPO_LOCATION="$LOCAL_DIRECTORY"
 else
-	echo "Need to configure either a remote or local repo"
-	exit 1
+	die 1 "Need to configure either a remote or local repo"
 fi
 
 # Canonicalise our location
@@ -125,14 +122,12 @@ if [[ $REMOTE_HOST ]]; then
 
 	# Make sure the remote host is usable
 	if ! ssh "${REMOTE_USER}@${REMOTE_HOST}" "echo -n"; then
-		echo "Can't run commands on remote host, aborting"
-		exit 99
+		die 99 "Can't run commands on remote host, aborting"
 	fi
 
 	# Sanity check for pre-existing repo
 	if ssh "${REMOTE_USER}@${REMOTE_HOST}" test -d "${REMOTE_DIRECTORY}/${HOSTNAME}"; then
-		echo "Repo already exists! Aborting..."
-		exit 5
+		die 5 "Repo already exists! Aborting..."
 	fi
 
 fi
@@ -151,6 +146,10 @@ elif [[ $YUM ]]; then
 	yum -y install borgbackup python34-pip
 fi
 
+if ! yq . </dev/null 2>/dev/null; then
+    pip3 install yq || die 12 "Could not install yq; aborting."
+fi
+
 WHICH=$(which borgmatic 2>/dev/null)
 if [[ ! -x "$BORGMATIC" && -z "$WHICH" ]]; then
 	pip3 install borgmatic
@@ -159,8 +158,7 @@ if [[ ! -x "$BORGMATIC" && -z "$WHICH" ]]; then
         if [[ -n "$WHICH" ]]; then
             BORGMATIC="$WHICH"
         else
-            echo "Cannot find borgmatic anywhere; aborting."
-            exit 9
+            die 9 "Cannot find borgmatic anywhere; aborting."
         fi
     fi
 fi
@@ -309,7 +307,7 @@ if [[ -z "$REMOTE_HOST" ]]; then
 	echo "$BORG_REPO" >> /etc/borgmatic/excludes.src
 fi
 
-/etc/borgmatic/build-excludes || exit 10
+/etc/borgmatic/build-excludes || die 10 "Could not build excludes list"
 
 # Make sure ordinary users can't read our passphrase etc.
 chmod -R o= /etc/borgmatic
@@ -319,7 +317,7 @@ chmod -R o= /etc/borgmatic
 if [[ "$REMOTE_HOST" ]]; then
 	# Make ourselves a dedicated ssh key with no passphrase
 	if [[ ! -f "$SSH_KEYFILE" ]]; then
-		ssh-keygen -N "" -f "$SSH_KEYFILE" -C "borgmatic root@${HOSTNAME}" || exit 2
+		ssh-keygen -N "" -f "$SSH_KEYFILE" -C "borgmatic root@${HOSTNAME}" || die 2 "Could not generate SSH key"
 	fi
 
 	# Copy our ssh public key to the remote server. We need to be logged in to
@@ -328,7 +326,7 @@ if [[ "$REMOTE_HOST" ]]; then
 	#
 	if ssh "${REMOTE_USER}@${REMOTE_HOST}" "/bin/sh -c exit"; then
 		# Remote server appears to be fully capable
-		ssh-copy-id -i "$SSH_KEYFILE" "${REMOTE_USER}@${REMOTE_HOST}" || exit $?
+		ssh-copy-id -i "$SSH_KEYFILE" "${REMOTE_USER}@${REMOTE_HOST}" || die $? "Could not copy SSH key to remote server"
 	else
 		# This is probably due to a restricted shell - try a stupider method
 		# NB this is racy AF. Make sure you have a way to get back in (e.g. password)
@@ -353,7 +351,7 @@ fi
 
 # We need to su properly to root, otherwise borg makes a mess in our homedir
 # But don't use "su -", because we want to keep our other environment.
-su -c "borg init -e keyfile ${BORG_REPO}" || exit 4
+su -c "borg init -e keyfile ${BORG_REPO}" || die 4 "Could not initialise repository"
 
 BORG_KEYFILE=/root/.config/borg/keys/$(ls -tr /root/.config/borg/keys | tail -1)
 
