Fall back to reading BORG_PASSPHRASE from config.yaml

diff --git a/borgsetup b/borgsetup
--- a/borgsetup
+++ b/borgsetup
@@ -144,7 +144,8 @@ if [[ $RECOVERY ]]; then
     echo "Entering recovery mode..."
     # In recovery mode, we must have a pre-existing configuration
     if [[ ! $BORG_PASSPHRASE ]]; then
-        die 5 "Recovery mode requires BORG_PASSPHRASE to be set; aborting"
+        BORG_PASSPHRASE=$(yq -r .storage.encryption_passphrase </etc/borgmatic/config.yaml)
+        [[ $BORG_PASSPHRASE ]] || die 5 "Recovery mode requires BORG_PASSPHRASE to be set; aborting"
     fi
     BORG_KEYFILE=/root/.config/borg/keys/$(ls -tr /root/.config/borg/keys | tail -1)
     if [[ ! $BORG_KEYFILE ]]; then
