Remove 'ansible -m script' support from install-docker; use --recurse-submodules in ztsetup

diff --git a/install-docker b/install-docker
--- a/install-docker
+++ b/install-docker
@@ -6,6 +6,11 @@ err_report() {
 }
 trap err_report ERR
 
+die() {
+    echo $2 >&2
+    exit $1
+}
+
 BRANCH=master
 DATA_DIR=/data
 
@@ -18,18 +23,7 @@ if [[ ! $DISABLE_IPTABLES ]]; then
     DISABLE_IPTABLES=true
 fi
 
-if [[ ! -x ${SCRIPT_DIR}/apt-repo ]]; then
-    # We are probably inside ansible; let's hope it forwarded our agent!
-    if ! grep -q github.com ~/.ssh/known_hosts; then
-        cat <<EOF >>~/.ssh/known_hosts
-github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
-EOF
-    fi
-    TMPDIR=$(mktemp -d)
-    cd $TMPDIR
-    git clone -b ${BRANCH} git@github.com:andrewgdotcom/admin-tools
-    SCRIPT_DIR=${TMPDIR}/admin-tools
-fi
+[[ -x ${SCRIPT_DIR}/apt-repo ]] || die 1 "Could not find apt-repo"
 
 ${SCRIPT_DIR}/apt-repo add docker "https://download.docker.com/linux/ubuntu xenial stable" https://download.docker.com/linux/ubuntu/gpg || true
 apt-get update
