Docker doesn't have a user; add image cleaner job

diff --git a/install-docker b/install-docker
--- a/install-docker
+++ b/install-docker
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+set -e
+
 BRANCH=master
 DATA_DIR=/data
 
@@ -30,7 +32,7 @@ DEBIAN_FRONTEND=noninteractive apt-get -y install docker-ce
 
 service docker stop
 
-DOCKER_HOME=$(getent passwd docker|awk -F: '{print $6}')
+DOCKER_HOME=/var/lib/docker
 
 # if DATA_DIR exists, move our storage there; it's probably got a lot more room
 if [[ -d "$DATA_DIR" ]]; then
@@ -123,6 +125,22 @@ EOF
 fi
 
 ufw allow in on docker0
+
+# Run daily docker image cleaner job
+cat >/etc/cron.daily/clean-images <<EOF
+#!/bin/bash
+# QAD script to clean up dangling docker images.
+
+for image in \$(docker images -f 'dangling=true' -q); do
+  docker rmi \$image | logger -t clean-images
+done
+
+# Belt and braces
+for image in \$(docker image list|grep '^sirensolutions/' | grep '<none>'| grep '(days|weeks?|months?) ago'|awk '{print \$3}'); do
+  docker rmi \$image | logger -t clean-images
+done
+EOF
+chmod +x /etc/cron.daily/clean-images
 
 ###############
 ### UNBOUND ###
