Filthy, unforgivable CentOS/RHEL 7 hackery

diff --git a/monkeyproof b/monkeyproof
--- a/monkeyproof
+++ b/monkeyproof
@@ -17,6 +17,10 @@ else
 	exit -1
 fi
 
+MS_HOME=/var/lib/monkeysphere
+MS_SPHERE_DIR=$MS_HOME/authentication/sphere
+MS_CORE_DIR=$MS_HOME/authentication/core
+
 # Support headless installation
 export DEBIAN_FRONTEND=noninteractive
 export MONKEYSPHERE_PROMPT=false
@@ -42,6 +46,42 @@ if [[ $APT ]]; then
   apt-get -y install monkeysphere dirmngr
 elif [[ $YUM ]]; then
   yum -y --setopt=skip_missing_names_on_install=False install monkeysphere
+  if rpm -q gnupg2 | egrep -q "gnupg2-2\.0\."; then
+    # https://people.kernel.org/monsieuricon/run-gnupg-2-2-17-on-your-el7-system
+    echo "RHEL/CentOS 7 sticky tape..."
+    yum install -y yum-plugin-copr
+    yum copr enable -y icon/lfit
+    yum install -y gnupg22-static
+    cat <<EOF > $MS_SPHERE_DIR/gpg.conf-2.2
+no-greeting
+list-options show-uid-validity
+keyid-format 0xlong
+agent-program   /opt/gnupg22/bin/gpg-agent
+dirmngr-program /opt/gnupg22/bin/dirmngr
+EOF
+    chown monkeysphere:monkeysphere $MS_SPHERE_DIR/gpg.conf-2.2
+    cat <<EOF > $MS_CORE_DIR/gpg.conf-2.2
+no-greeting
+keyid-format 0xlong
+agent-program   /opt/gnupg22/bin/gpg-agent
+dirmngr-program /opt/gnupg22/bin/dirmngr
+EOF
+    cat <<EOF > /etc/profile.d/monkeysphere-fix.sh
+export PATH=/opt/gnupg22/bin:$PATH
+EOF
+    cat <<EOF > /etc/profile.d/monkeysphere-fix.csh
+setenv PATH /opt/gnupg22/bin:$PATH
+EOF
+    # Migrate the monkeysphere core keyring to v2.2 format now, otherwise
+    # monkeysphere-authentication will fail due to lack of user interaction.
+    keyid=$(GNUPGHOME=$MS_CORE_DIR gpg --with-colons --list-secret-keys | \
+        awk -F: '/^fpr/ {print $10}')
+    GNUPGHOME=$MS_CORE_DIR gpg --yes --batch --edit-key $keyid || true
+    # And now perform a filthy, unforgivable patch against monkeysphere.
+    # THIS WILL BREAK ON UPGRADES
+    # ... but then this is CentOS 7 so it won't be getting any.
+    perl -pi.bak -e 's/(cut -d: -f10)/$1 | head -1/' /usr/share/monkeysphere/ma/add_certifier
+  fi
 fi
 
 # Monkeysphere in EPEL is broken by default; it sets the user shell to
